create database ShopSmart_Retail;
 use ShopSmart_Retail;
 select * from customer;
 select * from products;
 select * from purchase_history;
 
 -- What are the first_name, last_name, and email of all customers who signed up
-- in 2021?

 select first_name as nam,last_name,
 email,
 right(signup_date,4) as year
 from customer
 where  right(signup_date,4) =2021;
 describe customer;
 
-- How many customers are male and how many are female?
SELECT
 gender ,
 count(*) 
FROM customer as tottal_customer
group by gender;

-- List the product_name and price_per_unit
 -- for all products in the 'Meat'category.
 select product_name,
 price_per_unit,
 category
 from products
 where category="Meat";
 
 -- Which products have a price_per_unit between $10 and $20 (inclusive)?
 select product_name,price_per_unit
 from products
 where price_per_unit between 10 and 20;
 
 -- Find the customer_ids of all customers residing in 'Chicago'
 -- or 'Houston'.
 select customer_id, city from customer
 where city in('Chicago','Houston');
 
 -- What is the total quantity of 'Apple' products sold
 -- across all purchases?
 
SELECT SUM(ph.quantity) AS total_sold
FROM purchase_history AS ph
JOIN products AS p
    ON ph.product_id = p.product_id
WHERE LOWER(p.product_name) = 'apple';

-- Calculate the total_amount of all purchases made by customer_id 1.
 select * from purchase_history;
 select 
 sum(total_amount) as total_purchase
 from  purchase_history 
 where customer_id=1;
 
 -- Which category of products has the highest average price_per_unit?
 select category,
 avg(price_per_unit) as avg_price from products
 group by category
ORDER BY avg_price DESC;

-- What is the total revenue generated by each brand? 
select
 p.brand,
 sum(ph.total_amount) as Total_revenue 
from products as p
left join purchase_history as ph
on p.product_id=ph.product_id
group by brand 
order by Total_revenue desc;

-- How many purchases were made in each city where customers reside?
select
 c.city,count(ph.purchase_id) as total_purchase
from customer as c
left join purchase_history as ph
on c.customer_id=ph.customer_id
left join products as p
on ph.product_id=p.product_id
group by city
order by total_purchase desc;

--  For each purchase, what are the customer_id, first_name of the customer, 
-- and the product_name of the item purchased?
select 
c.customer_id,
 c.first_name, 
 COALESCE(p.product_name, 'No Purchase') AS product_name
from customer as c
left join purchase_history as ph
on c.customer_id=ph.customer_id
left join products as p
on ph.product_id=p.product_id
order by ph.purchase_id;

-- List the product_name, category, and total_amount for all purchases made by
-- customers whose last_name is 'Garcia'.
select 
P.product_name,
P.category,
ph.total_amount
from customer AS c
left join purchase_history as ph
ON c.customer_id = ph.customer_id
left join products as p
  ON ph.product_id = p.product_id
where c.last_name = 'Garcia'
order by purchase_id;

-- Which customers (display first_name, last_name) have purchased products
-- from the 'Dairy' category? (Ensure each customer is listed only once).
select
 c.first_name,
 c.last_name,p.category
from customer as c
left join purchase_history as ph 
on c.customer_id= ph.customer_id
left join products as p
on  ph.product_id= p.product_id
where p.category= 'Dairy'
ORDER BY c.last_name, c.first_name;
-- What is the total revenue generated from sales of products
--  in the 'Fruit' category?
select
 p.category,
 sum(ph.total_amount) as total_revenue
from products as p
left join purchase_history  as ph
on p.product_id =ph.product_id
where lower(category)='fruit';

-- Identify any products that have never been purchased. (Display their
-- product_name and brand).
select 
p. product_name,
p.brand from products as p
left join purchase_history as ph
on p.product_id=ph.product_id
where ph.product_id is null
order by p.product_name;
-- For each customer, what is their first_name, last_name, and the total sum of
-- total_amount they have spent across all their purchases?
select  
c.first_name, 
c.last_name ,
sum(ph.total_amount) as total_spent from customer  as c
left join purchase_history as ph
on c.customer_id=ph.customer_id
Group  by c.first_name, c.last_name
order by  total_spent desc;
 
 -- Which city has the highest total total_amount from all purchases
-- made by its resudents?
select  
c.city,
 sum(ph.total_amount) as total_spent 
 from customer as c
left join purchase_history as ph
on c.customer_id=ph.customer_id
group by c.city
order by total_spent desc;

-- List the first_name and last_name of customers who purchased 'Milk' and the
-- purchase_date of those transactions.
select 
c.first_name,
 c.last_name ,
 ph.purchase_date
from customer as c 
left join purchase_history as ph
on c.customer_id=ph.customer_id
left join products as p 
on ph.product_id=p.product_id
where lower(p.product_name)='milk'
order by ph.purchase_date;

-- What is the average total_amount per purchase for each gender?
SELECT c.gender,
       AVG(ph.total_amount) AS avg_total_spent
FROM customer AS c 
JOIN purchase_history AS ph
    ON c.customer_id = ph.customer_id
GROUP BY c.gender
ORDER BY avg_total_spent DESC;

-- For each brand, what is the total quantity of products sold?
select p.brand,
sum(ph.quantity) as total_quantity_sold 
from products as p
left join purchase_history as ph
on p.product_id= ph.product_id
group by p.brand
order by total_quantity_sold desc;
